<?php

/**
 * BaseRoles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Roles
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getRoles() Returns the current record's "Roles" collection
 * @method Roles               setName()  Sets the current record's "name" value
 * @method Roles               setRoles() Sets the current record's "Roles" collection
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     PQASBTM
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('roles');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Logins as Roles', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}