<?php

/**
 * BaseStrategy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Sessionstrategy
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getSessionstrategy() Returns the current record's "Sessionstrategy" collection
 * @method Strategy            setName()            Sets the current record's "name" value
 * @method Strategy            setSessionstrategy() Sets the current record's "Sessionstrategy" collection
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     Mohamed Sithik
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStrategy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('strategy');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sessions as Sessionstrategy', array(
             'local' => 'id',
             'foreign' => 'strategy_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}