<?php

/**
 * BaseLogins
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $status
 * 
 * @method string getName()     Returns the current record's "name" value
 * @method string getUsername() Returns the current record's "username" value
 * @method string getPassword() Returns the current record's "password" value
 * @method string getEmail()    Returns the current record's "email" value
 * @method string getStatus()   Returns the current record's "status" value
 * @method Logins setName()     Sets the current record's "name" value
 * @method Logins setUsername() Sets the current record's "username" value
 * @method Logins setPassword() Sets the current record's "password" value
 * @method Logins setEmail()    Sets the current record's "email" value
 * @method Logins setStatus()   Sets the current record's "status" value
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     PQASBTM
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogins extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logins');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}