<?php

/**
 * BaseProjectCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string          getName() Returns the current record's "name" value
 * @method ProjectCategory setName() Sets the current record's "name" value
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     PQASBTM
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}