<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Sessionstatus
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getSessionstatus() Returns the current record's "Sessionstatus" collection
 * @method Status              setName()          Sets the current record's "name" value
 * @method Status              setSessionstatus() Sets the current record's "Sessionstatus" collection
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     PQASBTM
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sessions as Sessionstatus', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}