<?php

/**
 * BaseProjectCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property date $startdate
 * @property date $enddate
 * @property string $completetag
 * @property Doctrine_Collection $Projectlink
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method date                getStartdate()   Returns the current record's "startdate" value
 * @method date                getEnddate()     Returns the current record's "enddate" value
 * @method string              getCompletetag() Returns the current record's "completetag" value
 * @method Doctrine_Collection getProjectlink() Returns the current record's "Projectlink" collection
 * @method ProjectCategory     setName()        Sets the current record's "name" value
 * @method ProjectCategory     setStartdate()   Sets the current record's "startdate" value
 * @method ProjectCategory     setEnddate()     Sets the current record's "enddate" value
 * @method ProjectCategory     setCompletetag() Sets the current record's "completetag" value
 * @method ProjectCategory     setProjectlink() Sets the current record's "Projectlink" collection
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     Mohamed Sithik
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('startdate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('enddate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('completetag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sessions as Projectlink', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}