<?php

/**
 * ProjectCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectCategory');
    }
}