<?php

/**
 * RolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Roles');
    }
}