<?php

/**
 * Sessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PQASBTM
 * @subpackage model
 * @author     PQASBTM
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Sessions extends BaseSessions
{
public function getFileSlug()
{
  return sbtm::slugify(trim($this->getSessionname()));
}

public function getFilenmaeSlug($text)
{
  return sbtm::slugify($this->$text);
}


}