<?php

/**
 * SessionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sessions');
    }
}