<?php

/**
 * StrategyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrategyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrategyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Strategy');
    }
}