<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/06/01 10:28:02
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'E:/development/sfprojects/SBTM/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseloginsformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/base/BaseLoginsFormFilter.class.php',
  'baseprojectcategoryformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/base/BaseProjectCategoryFormFilter.class.php',
  'baserolesformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/base/BaseRolesFormFilter.class.php',
  'baseformfilterdoctrine' => 'E:/development/PQASBTM/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'loginsformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/LoginsFormFilter.class.php',
  'projectcategoryformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/ProjectCategoryFormFilter.class.php',
  'rolesformfilter' => 'E:/development/PQASBTM/lib/filter/doctrine/RolesFormFilter.class.php',
  'baseform' => 'E:/development/PQASBTM/lib/form/BaseForm.class.php',
  'baseloginsform' => 'E:/development/PQASBTM/lib/form/doctrine/base/BaseLoginsForm.class.php',
  'baseprojectcategoryform' => 'E:/development/PQASBTM/lib/form/doctrine/base/BaseProjectCategoryForm.class.php',
  'baserolesform' => 'E:/development/PQASBTM/lib/form/doctrine/base/BaseRolesForm.class.php',
  'baseformdoctrine' => 'E:/development/PQASBTM/lib/form/doctrine/BaseFormDoctrine.class.php',
  'loginsform' => 'E:/development/PQASBTM/lib/form/doctrine/LoginsForm.class.php',
  'projectcategoryform' => 'E:/development/PQASBTM/lib/form/doctrine/ProjectCategoryForm.class.php',
  'rolesform' => 'E:/development/PQASBTM/lib/form/doctrine/RolesForm.class.php',

  // project_model
  'baselogins' => 'E:/development/PQASBTM/lib/model/doctrine/base/BaseLogins.class.php',
  'baseprojectcategory' => 'E:/development/PQASBTM/lib/model/doctrine/base/BaseProjectCategory.class.php',
  'baseroles' => 'E:/development/PQASBTM/lib/model/doctrine/base/BaseRoles.class.php',
  'logins' => 'E:/development/PQASBTM/lib/model/doctrine/Logins.class.php',
  'loginstable' => 'E:/development/PQASBTM/lib/model/doctrine/LoginsTable.class.php',
  'projectcategory' => 'E:/development/PQASBTM/lib/model/doctrine/ProjectCategory.class.php',
  'projectcategorytable' => 'E:/development/PQASBTM/lib/model/doctrine/ProjectCategoryTable.class.php',
  'roles' => 'E:/development/PQASBTM/lib/model/doctrine/Roles.class.php',
  'rolestable' => 'E:/development/PQASBTM/lib/model/doctrine/RolesTable.class.php',

  // application
  'myuser' => 'E:/development/PQASBTM/apps/backend/lib/myUser.class.php',

  // modules
);
