# apps/frontend/modules/job/config/view.yml
indexSuccess:
  stylesheets: [sbtms.css]
newSuccess:
  stylesheets: [sbtm.css]
editSuccess:
  stylesheets: [sbtm.css]
showSuccess:
  stylesheets: [sbtm.css]
uploadsSuccess:
  stylesheets: [sbtm.css]
reviewSuccess:
  stylesheets: [sbtm.css]
sessionreadonlySuccess:
  stylesheets: [sbtm.css]
