# apps/frontend/modules/job/config/view.yml
indexSuccess:
  stylesheets: [sbtms.css]
homeSuccess:
  stylesheets: [sbtm.css]
loginSuccess:
  stylesheets: [sbtm.css]
projectadminSuccess:
  stylesheets: [sbtm.css]
useradminSuccess:
  stylesheets: [sbtm.css]
userdetailSuccess:
  stylesheets: [sbtm.css]
showSuccess:
  stylesheets: [sbtm.css]
sessionsSuccess:
  stylesheets: [sbtm.css]
uploadsSuccess:
  stylesheets: [sbtm.css]
usermysessionSuccess:
  stylesheets: [sbtm.css]
adminmysessionSuccess:
  stylesheets: [sbtm.css]
reportingSuccess:
  stylesheets: [sbtm.css]
sessionlistSuccess:
  stylesheets: [sbtm.css]
managesessionSuccess:
  stylesheets: [sbtm.css]
burndownchartSuccess:
  stylesheets: [sbtm.css]
