<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/26 05:01:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pqasbtm',
  'username' => 'root',
  'password' => 'admin',
  'name' => 'doctrine',
)),);
