<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/01 10:33:16
sfConfig::add(array(
  'mod_projectcategory_enabled' => true,
  'mod_projectcategory_view_class' => 'sfPHP',
));
