<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/22 05:29:29
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
