<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/21 12:07:09
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
