ProjectCategory:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    startdate: { type: date}
    enddate: { type: date}
    completetag: {type: string(255)}

Role:
   actAs: { Timestampable: ~ }
   columns:
    name: { type: string(255), notnull: true, unique: true }

Logins:
   actAs: { Timestampable: ~ }
   columns:
    name: { type: string(255), notnull: true, unique: true }
    username: { type: string(255), notnull: true, unique: true }
    password: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }
    role_id: { type: integer, notnull: true }
    islocked: { type: string(255), notnull: true}
   relations:
    Role: { onDelete: CASCADE, local: role_id, foreign: id, foreignAlias: Role } 

   
Status:
   actAs: { Timestampable: ~ }
   columns:
    name: { type: string(255), notnull: true, unique: true }
    
Sessions:
   actAs: { Timestampable: ~ }
   columns:
    sessionname: { type: string(255), notnull: true, unique: true }
    charter: { type: string(255), notnull: true }
    areas: { type: string(800), notnull: true }
    testnotes: { type: string(255)}
    ready: { type: string(255), notnull: true}
    tester: { type: string(255)}
    status_id:  { type: integer, notnull: true }
    project_id:  { type: integer, notnull: true }
    strategy_id:  { type: integer, notnull: true }
    todochange_at:  { type: datetime, notnull: false }

   relations:
    Status: { onDelete: CASCADE, local: status_id, foreign: id, foreignAlias: Sessionstatus } 
    ProjectCategory: { onDelete: CASCADE, local: project_id, foreign: id, foreignAlias: Projectlink } 
    Strategy: { onDelete: CASCADE, local: strategy_id, foreign: id, foreignAlias: Sessionstrategy } 

Strategy:
   actAs: { Timestampable: ~ }
   columns:
    name: { type: string(255), notnull: true, unique: true }  
